# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09b668d946b8df5ed32d75bf524cdf7b0fdfdf36c0ed53d902221d2793c484fae7bf3aa5366c9fce7a44fd7fef2815a167bb308d17e432803f7e5b72b2fb1a2c

test:
  secret_key_base: 327fca8a8c7fa18f3f927f0825df8fab0e1e069b02441ab11a059d3e67a9ebb362f7155361f93ee4a9e3575cd0786ca0fb54220b4ea7f53d47509ad729ae60e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
